#!/bin/sh
./gameboy BROKER APPEARED_POKEMON Jolteon 2 2 1
./gameboy BROKER APPEARED_POKEMON Flareon 4 6 1

./gameboy BROKER APPEARED_POKEMON Umbreon 10 6 1
./gameboy BROKER APPEARED_POKEMON Espeon 7 1 1
./gameboy BROKER APPEARED_POKEMON Vaporeon 4 10 1